-- ============================================
-- SEED SQL - Prefeitura Node Data
-- Rodar no Supabase SQL Editor
-- ============================================
-- 1. Criar tabela de feedbacks
CREATE TABLE IF NOT EXISTS feedbacks (
    id bigint generated by default as identity primary key,
    sender text,
    name text,
    message text not null,
    timestamp timestamp with time zone default timezone('utc'::text, now()),
    category text,
    region text,
    urgency text,
    sentiment text,
    topic text,
    status text default 'aberto',
    resolved_at text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 2. Criar tabela de config
DROP TABLE IF EXISTS config;
CREATE TABLE config (
    id bigint generated by default as identity primary key,
    type text not null,
    name text not null,
    color text,
    count int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 3. Inserir Categorias Municipais
INSERT INTO config (type, name, color)
VALUES ('category', 'Infraestrutura & Obras', '#f59e0b'),
    ('category', 'Saúde & Atendimento', '#ec4899'),
    ('category', 'Educação & Escolas', '#8b5cf6'),
    ('category', 'Segurança Pública', '#ef4444'),
    ('category', 'Limpeza & Meio Ambiente', '#10b981'),
    ('category', 'Transporte & Mobilidade', '#3b82f6');
-- 4. Inserir Regiões/Bairros
INSERT INTO config (type, name)
VALUES ('region', 'Centro'),
    ('region', 'Conjunto Dona Angelina'),
    ('region', 'Conjunto João Guerreiro'),
    ('region', 'Conjunto Bela Vista'),
    ('region', 'Conjunto Santa Terezinha'),
    ('region', 'Conjunto Bom Gosto'),
    ('region', 'Conjunto Valdomiro Favero'),
    ('region', 'Conjunto Jardim Bom Sucesso'),
    ('region', 'Vila Rural Menino Jesus'),
    ('region', 'Herculandia'),
    ('region', 'Conjunto Eldorado');
-- 5. Habilitar RLS (Row Level Security) - opcional
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;
-- 6. Criar políticas de acesso público (para anon key)
CREATE POLICY "Allow public read feedbacks" ON feedbacks FOR
SELECT USING (true);
CREATE POLICY "Allow public insert feedbacks" ON feedbacks FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update feedbacks" ON feedbacks FOR
UPDATE USING (true);
CREATE POLICY "Allow public read config" ON config FOR
SELECT USING (true);
CREATE POLICY "Allow public insert config" ON config FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update config" ON config FOR
UPDATE USING (true);
CREATE POLICY "Allow public delete config" ON config FOR DELETE USING (true);
